query CartLinesDiscountsGenerateRunInput {
  cart {
    freeGiftVariantId: attribute(key: "_pgy_free_gift_variant_id") {
      value
    }
    tieredGiftVariantId: attribute(key: "_pgy_tiered_gift_variant_id") {
      value
    }
    giftDiscountLabel: attribute(key: "_pgy_gift_discount_label") {
      value
    }
    comboDiscounts: attribute(key: "_pgy_combo_discounts") {
      value
    }
    comboDiscountEnabled: attribute(key: "_pgy_combo_discount_enabled") {
      value
    }
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
      cost {
        subtotalAmount {
          amount
        }
      }
      freeGift: attribute(key: "_pgy_free_gift") {
        value
      }
      tieredGift: attribute(key: "_pgy_tiered_gift") {
        value
      }
    }
  }
}
